#!/usr/bin/env python3
"""Create deterministic assets and an OpenToonz script for the VM scene test."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import struct
import zlib
from pathlib import Path
from typing import Callable


WIDTH = 640
HEIGHT = 360
FRAME_COUNT = 12

RGBA = tuple[int, int, int, int]
PixelTest = Callable[[int, int], bool]

SHAPES: tuple[tuple[str, RGBA], ...] = (
    ("circle", (232, 65, 56, 255)),
    ("square", (52, 168, 83, 255)),
    ("triangle", (50, 103, 220, 255)),
)


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    return (
        struct.pack(">I", len(payload))
        + kind
        + payload
        + struct.pack(">I", zlib.crc32(kind + payload) & 0xFFFFFFFF)
    )


def write_rgba_png(path: Path, pixel_test: PixelTest, color: RGBA) -> None:
    """Write an RGBA PNG with a transparent background using only stdlib."""
    rows = bytearray()
    transparent = bytes((0, 0, 0, 0))
    opaque = bytes(color)
    for y in range(HEIGHT):
        rows.append(0)  # PNG filter: None
        for x in range(WIDTH):
            rows.extend(opaque if pixel_test(x, y) else transparent)

    ihdr = struct.pack(">IIBBBBB", WIDTH, HEIGHT, 8, 6, 0, 0, 0)
    content = (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", zlib.compress(bytes(rows), 9))
        + _png_chunk(b"IEND", b"")
    )
    path.write_bytes(content)


def circle_test(frame: int) -> PixelTest:
    cx, cy, radius = 90 + frame * 28, 90, 42
    return lambda x, y: (x - cx) ** 2 + (y - cy) ** 2 <= radius**2


def square_test(frame: int) -> PixelTest:
    left, top, size = 275, 36 + frame * 17, 78
    return lambda x, y: left <= x < left + size and top <= y < top + size


def triangle_test(frame: int) -> PixelTest:
    center_x = 515 - frame * 18
    center_y = 250 + round(22 * math.sin(frame * math.pi / 5.5))
    a = (center_x, center_y - 54)
    b = (center_x - 52, center_y + 40)
    c = (center_x + 52, center_y + 40)

    def sign(px: int, py: int, p1: tuple[int, int], p2: tuple[int, int]) -> int:
        return (px - p2[0]) * (p1[1] - p2[1]) - (p1[0] - p2[0]) * (
            py - p2[1]
        )

    def inside(x: int, y: int) -> bool:
        d1, d2, d3 = sign(x, y, a, b), sign(x, y, b, c), sign(x, y, c, a)
        return not ((d1 < 0 or d2 < 0 or d3 < 0) and (d1 > 0 or d2 > 0 or d3 > 0))

    return inside


PIXEL_TESTS: dict[str, Callable[[int], PixelTest]] = {
    "circle": circle_test,
    "square": square_test,
    "triangle": triangle_test,
}


def javascript_string(path: Path) -> str:
    return str(path.resolve()).replace("\\", "\\\\").replace('"', '\\"')


def project_xml() -> str:
    folders = ("inputs", "drawings", "scenes", "scripts", "extras", "outputs", "palettes")
    entries = "\n".join(
        f'    <folder name="{folder}" path="{folder}"/>' for folder in folders
    )
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<project>\n"
        "  <version>70 1</version>\n"
        "  <folders>\n"
        f"{entries}\n"
        "  </folders>\n"
        "</project>\n"
    )


def scenes_xml() -> str:
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        '<parentProject type="projectFolder">..</parentProject>\n'
    )


def automation_script(root: Path) -> str:
    drawing = root / "drawings"
    scene_path = root / "scenes" / "animated-shapes.tnz"
    level_lines = []
    cell_lines = []
    for column, (name, _color) in enumerate(SHAPES):
        first_frame = drawing / f"{name}.0001.png"
        variable = f"{name}Level"
        level_lines.append(
            f'var {variable} = scene.loadLevel("{name.title()}", '
            f'"{javascript_string(first_frame)}");'
        )
        cell_lines.append(
            f"  scene.setCell(frame, {column}, {variable}, frame + 1);"
        )

    return "\n".join(
        [
            "// Generated by OT-Automaton. Runs through OpenToonz's built-in QtScript API.",
            'print("OT_AUTOMATON_STEP script-started");',
            "var scene = new Scene();",
            'print("OT_AUTOMATON_STEP scene-created");',
            *level_lines,
            'print("OT_AUTOMATON_STEP levels-loaded");',
            f"for (var frame = 0; frame < {FRAME_COUNT}; ++frame) {{",
            *cell_lines,
            "}",
            'print("OT_AUTOMATON_STEP cells-set");',
            f'scene.save("{javascript_string(scene_path)}");',
            'print("OT_AUTOMATON_STEP scene-saved");',
            'print("OT_AUTOMATON_SCENE_CREATED frames=" + scene.frameCount +',
            '      " columns=" + scene.columnCount);',
            "",
        ]
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def create_project(root: Path) -> dict[str, object]:
    root = root.resolve()
    for folder in (
        "inputs",
        "drawings",
        "scenes",
        "scripts",
        "extras",
        "outputs",
        "palettes",
        "evidence",
    ):
        (root / folder).mkdir(parents=True, exist_ok=True)

    (root / "animated-shapes_otprj.xml").write_text(project_xml(), encoding="utf-8")
    for folder in ("drawings", "scenes", "scripts", "outputs"):
        (root / folder / "scenes.xml").write_text(scenes_xml(), encoding="utf-8")

    assets = []
    for name, color in SHAPES:
        for frame in range(FRAME_COUNT):
            path = root / "drawings" / f"{name}.{frame + 1:04d}.png"
            write_rgba_png(path, PIXEL_TESTS[name](frame), color)
            assets.append(
                {
                    "path": str(path.relative_to(root)),
                    "sha256": sha256(path),
                }
            )

    script_path = root / "scripts" / "create_scene.toonzscript"
    script_path.write_text(automation_script(root), encoding="utf-8")
    readme = root / "README.md"
    readme.write_text(
        "# OT-Automaton animated-shapes acceptance project\n\n"
        "Open `scenes/animated-shapes.tnz` in OpenToonz. The scene contains "
        "three independently animated raster levels: a red circle, green square, "
        "and blue triangle. Source frames are in `drawings/`; representative "
        "renders are in `outputs/`; CI evidence is in `evidence/`.\n",
        encoding="utf-8",
    )

    manifest: dict[str, object] = {
        "schema_version": 1,
        "test": "animated-shapes",
        "canvas": {"width": WIDTH, "height": HEIGHT},
        "frame_count": FRAME_COUNT,
        "levels": [
            {"name": name, "rgba": list(color), "column": index}
            for index, (name, color) in enumerate(SHAPES)
        ],
        "assets": assets,
        "scene": "scenes/animated-shapes.tnz",
        "automation_script": "scripts/create_scene.toonzscript",
        "representative_render_frames": [1, FRAME_COUNT // 2 + 1, FRAME_COUNT],
    }
    (root / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_root", type=Path)
    args = parser.parse_args()
    manifest = create_project(args.project_root)
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
